services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      GENERIC_TIMEZONE: Europe/Berlin
      TZ: Europe/Berlin
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      N8N_SECURE_COOKIE: "false"
      N8N_RESTRICT_FILE_ACCESS_TO: /home/node/data;/home/node/.n8n-files
    volumes:
      - n8n_data:/home/node/.n8n
      - /home/john/Yahoo-Finance-Wrapper:/home/node/data
    restart: unless-stopped
    networks:
      - appnet

  yfinance-wrapper:
    build: .
    container_name: yfinance-wrapper
    ports:
      - "7000:7000"
    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:

volumes:
  n8n_data:
